### ISSUE TITLE
Mobile menu doesn't show

### ISSUE THREAD

**Issue by clarisse83** [tbela99/gzip#18]
Hi! When enabling Gzip, my menu disappear on mobile. I use Gantry's particle 'mobile menu'. It works on Deskop, except when reducing the size of the window. What can I do?

**Comment by tbela99** [comment]
That might be a javascript related issue. You have to use your browser console to debug that issue

**Comment by clarisse83** [comment]
I runned tests. 

A- When enabling Gzip and turning 'http cache' off, I have no errors or warnings but the menu doesn't show.

B- When enabling Gzip and turning 'http cache' on, I have no errors, just a few warnings - the menu still doesn't show:

The two first warnings are related to rocket-loader.min.js from Cloudflare. Is it better to turn it off?

1- A preload for 'https://www.mysite.com/7BOCz/00000...002irL5_/cache/z/ssl/www.mysite.com/css/1/000...02HebG_.css' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

2- A preload for 'https://www.mysite.com/7BOCz/N@8d8/cache/z/ssl/www.mysite.com/js/1/0000...039DPp_.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

Then I have a few more warnings:

3- A preload for 'https://www.mysite.com/7BOCz/000000...0002irL5_/cache/z/ssl/www.mysite.com/css/1/000...0002HebG_.css' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

4- The resource https://www.mysite.com/7BOCz/00000...002irL5_/cache/z/ssl/www.mysite.com/css/1/000...002HebG_.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

5- The resource https://www.mysite.com/7BOCz/N@8d8/cache/z/ssl/www.mysite.com/js/1/00000...039DPp_.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

6- The resource /favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by tbela99** [comment]
You should turn off rocket loader and any other cloudflare optimization

**Comment by tbela99** [comment]
I mean you need to disable cloudflare minification and compression of css and javascript

**Comment by clarisse83** [comment]
I removed the minifications of CSS and JavaScript on Cloudflare and the rocket loader. 

The listed issues are not related to Cloudflare. I found that these warnings are related to the 'all supported types' parameter of the HTTP/2 push. 
When I select stylesheet, JavaScript, fonts and media, these preload warnings disappear. 

Apart from the menu problem that disappears, everything else works well.

**Comment by tbela99** [comment]
Your problem might come from the fact that you have enabled sub resource integrity (in the first tab of the settings page). This will prevent files from loading if they are tampered between your webserver and the client browser.
-> if cloudflare alters the file in some ways (minfication, etc...) the file will not load and you should see an error in your browser console

**Comment by clarisse83** [comment]
No sub resource integrity is disabled. I tried to turn off all the settings but the menu is still disappearing. Do you think it's possible than a css/js doesn't like to be preloaded by Gzip?
I'm gonna try the plugin in a local version to see if the problem comes from Cloudflare.

**Comment by clarisse83** [comment]
So when enabling error reporting both on the online and local version of the site there are several issues reported:

Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 239

Warning: Invalid argument supplied for foreach() in /home/sitename/www/plugins/system/gzip/helper.php on line 828

Warning: Invalid argument supplied for foreach() in /home/sitename/www/plugins/system/gzip/helper.php on line 836

Warning: file_get_contents(cache/z/ssl/www.sitename.com/css/1/-574454190-build.php): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/helper.php on line 1223

Warning: getimagesize(/7BOCz/UCYTR/components/com_k2/images/system/featuredItem.png): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/helper.php on line 1571

Warning: getimagesize(/7BOCz/hvEbG/components/com_k2/images/system/stripes.png): failed to open stream: No such file or directory in /home/sitenameb/www/plugins/system/gzip/helper.php on line 1571

Warning: getimagesize(/7BOCz/wYDxu/components/com_k2/images/fugue/feed.png): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/helper.php on line 1571

Warning: getimagesize(/7BOCz/0000...0036tcQ_/components/com_k2/images/fugue/globe.png): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/helper.php on line 1571

Warning: getimagesize(/7BOCz/000...001VCPE_/components/com_k2/images/fugue/mail.png): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/helper.php on line 1571

Warning: Invalid argument supplied for foreach() in /home/sitename/www/plugins/system/gzip/helper.php on line 1901

Warning: Invalid argument supplied for foreach() in /home/sitename/www/plugins/system/gzip/helper.php on line 1909

Warning: file_put_contents(cache/z/ssl/www.sitename.com/ch/1/0000...02irL5_-000...02HebG_.css.checksum.php): failed to open stream: File name too long in /home/sitename/www/plugins/system/gzip/helper.php on line 135

**Comment by tbela99** [comment]
It looks like a permission issue to me

**Comment by clarisse83** [comment]
755 on folders and 604 on files

**Comment by tbela99** [comment]
I don't know if this might be related to #12 but I am currently working on fixing it

**Comment by clarisse83** [comment]
it looks similar

**Comment by tbela99** [comment]
This definitely looks like a permission issue. This file is used to track whenever an update is necessary.


_Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 239_

**Comment by tbela99** [comment]
It should be fixed in this branch https://github.com/tbela99/gzip/tree/file_not_found.

**Comment by tbela99** [comment]
It should be fixed now

**Comment by clarisse83** [comment]
No, it's not fixed. My menu is still not showing and there are still a few errors:

Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 162

Warning: file_get_contents(cache/z/ssl/www.sitename.com/css/1/-574454190-build.php): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/helper.php on line 812

Warning: getimagesize(/7BOCz/hvEbG/components/com_k2/images/system/stripes.png): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/helper.php on line 1027

Warning: file_put_contents(cache/z/ssl/www.sitename.com/ch/1/00002irL5_-0002HebG_.css.checksum.php): failed to open stream: File name too long in /home/sitename/www/plugins/system/gzip/helper.php on line 109

**Comment by tbela99** [comment]
Please delete the Joomla cache and try again. If the problem persists try testing with incognito mode

**Comment by tbela99** [comment]
_Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 162_

It looks like you are not using the right version as that line does not contain the code that tries to open file worker version.

https://github.com/tbela99/gzip/blob/master/gzip.php#L162

**Comment by clarisse83** [comment]
I deleted all the cache (joomla, browser, cloudflare) and I tried with incognito mode (chrome and safari) but there are still a few errors.

On administration + site:

Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 162

I updated gzip.php again just in case something didn't work the first time with the ftp transfert.
I checked line 162 and I've got the same code than you:

$script = str_replace(['{CACHE_NAME}', '{defaultStrategy}', '{scope}', '{debug}'], ['v_'.$this->worker_id, empty($this->options['pwa_network_strategy']) ? 'nf' : $this->options['pwa_network_strategy'], \JUri::root(true) . '/', $this->worker_id.(empty($this->options['debug_pwa']) ? '.min' : '')], file_get_contents(__DIR__.'/worker/dist/browser.min.js'));

On site only:

Warning: file_put_contents(cache/z/ssl/www.sitename.com/ch/1/00...002irL5_-00...002HebG_.css.checksum.php): failed to open stream: File name too long in /home/sitename/www/plugins/system/gzip/helper.php on line 109

Warning: file_put_contents(cache/z/ssl/www.sitename.com/ch/1/000...02irL5_-000...002HebG_.css.checksum.php): failed to open stream: File name too long in /home/sitename/www/plugins/system/gzip/helper.php on line 109

**Comment by tbela99** [comment]
What I was saying is you need to download and install the new release that has the issue fixed using this link  https://github.com/tbela99/gzip/archive/master.zip

**Comment by clarisse83** [comment]
I just installed the new version. The previous errors were fixed. Two new ones showed up and still no menu.

Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 239

Warning: file_put_contents(cache/z/ssl/www.sitename.com/ch/1/000...02irL5_-000...002HebG_.css.checksum.php): failed to open stream: File name too long in /home/sitename/www/plugins/system/gzip/helper.php on line 135

**Comment by tbela99** [comment]
Try clearing the cache. This time it should work.

**Comment by clarisse83** [comment]
I cleaned the cache, I even clean the ch/1 file. No change. No menu and the same errors on line 239 and 135.

**Comment by tbela99** [comment]
I will take another look at that

**Comment by tbela99** [comment]
I think the real problem is that  _File name too long_ error. I will try to fix it.

**Comment by tbela99** [comment]
How many characters are in the name of that file? _cache/z/ssl/www.sitename.com/ch/1/000...02irL5_-000...002HebG_.css.checksum.php_. The file length limit is usually 255 characters, If the name is longer than that then the file creation might fail.

**Comment by clarisse83** [comment]
from cache to php there are 412 characters

**Comment by tbela99** [comment]
that is way too long. that is why the file is not created / read. Is the sitename too long or is the file name or the path?

**Comment by clarisse83** [comment]
i only have 8 characters for the site name, the problem is the number of zero:

ch/1/0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002irL5_-0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002HebG_.css.checksum.php

**Comment by tbela99** [comment]
Well that is bad. I have an idea  why there are so much 0. I will try a fix for that

**Comment by clarisse83** [comment]
thanks

**Comment by tbela99** [comment]
I have added a fix to remove those 0 in this fix

https://github.com/tbela99/gzip/archive/file_not_found.zip

Can you test it on your local dev? You need to download and install it and clen the cache.

Thanks

**Comment by tbela99** [comment]
The filename should be 2irL5_-2HebG_.css.checksum.php
I will do few tests to validate the issue has been cleared and then merge those changes sometimes this week.

**Comment by tbela99** [comment]
I think the issue is fixed now. Please feel free to reopen if this is not the case.

**Comment by clarisse83** [comment]
Unfortunately, it's not fixed :) I just installed your new version but now when enabling Gzip, joomla administration and the site is not working anymore and there is this error message:

Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 239

I don't know if it's related but I noticed I don't have the file 'app' in the cache file. I only have 'ssl'.

**Comment by tbela99** [comment]
I just made an update a few moment ago. That update fixed some edge case issues. Did you try that one? You can download it from here https://github.com/tbela99/gzip/archive/master.zip

**Comment by tbela99** [comment]
Do not forget to clean the cache after installing that version and before you test it.

**Comment by clarisse83** [comment]
Same error on line 239

**Comment by tbela99** [comment]
What is the file name?

**Comment by tbela99** [comment]
I mean the file name that causes the error?

**Comment by clarisse83** [comment]
Warning: file_get_contents(/home/sitename/www/cache/z/app/www.sitename.com/worker_version): failed to open stream: No such file or directory in /home/sitename/www/plugins/system/gzip/gzip.php on line 239

**Comment by tbela99** [comment]
You mean that is the only error appearing now?

**Comment by clarisse83** [comment]
Yes, this is the only error appearing. But I don't have access to joomla administration anymore once enabling Gzip.

**Comment by tbela99** [comment]
If you have access to the database, search the extension in the #__extensions table and set the published state to 0. I guess you might have enabled a security setting in the security tab of the plugin

**Comment by tbela99** [comment]
I mean you set the published state of the gzip plugin to 0 in the #__extensions table

**Comment by clarisse83** [comment]
That's what I did to turn it off.

**Comment by tbela99** [comment]
I am able to reproduce the problem. You have pwa features disabled. In the plugin option / PWA app tab.
Enable pwa is set to No. That causes the notice to appear

I fix that notice now

**Comment by clarisse83** [comment]
Yes it is disabled

**Comment by tbela99** [comment]
please try with this update https://github.com/tbela99/gzip/archive/file_not_found.zip

**Comment by clarisse83** [comment]
After enabling Gzip, the administration is working perfectly but not the website. These errors are listed:

Warning: array_map(): Argument #2 should be an array in /home/sitename/www/plugins/system/gzip/gzip.php on line 279

Warning: array_merge(): Argument #1 is not an array in /home/sitename/www/plugins/system/gzip/gzip.php on line 280

Warning: array_filter() expects parameter 1 to be array, null given in /home/sitename/www/plugins/system/gzip/gzip.php on line 280

Warning: implode(): Invalid arguments passed in /home/sitename/www/plugins/system/gzip/gzip.php on line 280

Warning: Invalid argument supplied for foreach() in /home/sitename/www/plugins/system/gzip/gzip.php on line 315

**Comment by tbela99** [comment]
okay, I will fix that today

**Comment by tbela99** [comment]
Can you check this fix again ? https://github.com/tbela99/gzip/archive/file_not_found.zip

Thanks

**Comment by clarisse83** [comment]
With this version there are no problem of access to the administration or to the website. 
The menu button still disappears on mobile.
When choosing maximum error report in global configuration, there is this error:

Notice: Undefined index: cdn in /home/sitename/www/plugins/system/gzip/gzip.php on line 274

**Comment by tbela99** [comment]
I am on it. I guess you might have some settings missing in your config

**Comment by tbela99** [comment]
try again with this release please https://github.com/tbela99/gzip/archive/file_not_found.zip

**Comment by tbela99** [comment]
if the menu does not show up this can be a css issue. If a css file contains an error like a missing _}_ this can break your website. You can download the css file and try to debug it in an IDE. I would suggest vscode or phpstorm if you don't have any yet :)

**Comment by clarisse83** [comment]
No more errors :) No menu too but you're probably right about a css file

**Comment by tbela99** [comment]
Thank you for your help!
